# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CsvLayersList
                                 A QGIS plugin
 list all csv and tsv files and load them into QGIS canvas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-27
        copyright            : (C) 2023 by fajr.tech
        email                : contact@fajr.tech
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CsvLayersList class from file CsvLayersList.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .csv_layers_list import CsvLayersList
    return CsvLayersList(iface)
